- name: Purge openjdk*
  command: apt-get purge -y openjdk*

- name: Add java apt repositories
  apt_repository: repo="ppa:webupd8team/java" state=present

- name: Automatically select the Oracle License
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections

- name: Install Oracle Java
  apt: pkg=oracle-java8-installer
