---
- name: Download dropbox
  get_url: url={{ dropbox_url_ubuntu_deb }} dest={{ dropbox_tmp_deb }}

- name: Install dropbox for Debian OS family
  apt: deb={{ dropbox_tmp_deb }}

- name: Remove dropbox apt repositories
  file: path=/etc/apt/sources.list.d/dropbox.list state=absent
